server:
  port: 8080

spring:
  application:
    name: jobshin

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  mvc:
    hidden-method:
      filter:
        enabled: true

  datasource:
    url: jdbc:mysql://jobshin-rds-db.cjamy8sw6127.ap-northeast-2.rds.amazonaws.com:3306/jobshin_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 1q2w3e4r

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

alan:
  api:
    default-url: https://kdt-api-function.azurewebsites.net/api/v1/question
    client-id: 16a4fd21-9355-461c-bc2b-f0d5a3172d6d